apiVersion: v1
kind: ConfigMap
metadata:
  name: common-probing-store
  namespace: prod
data:
  DB_HOST: "probing-store-prod.cluster-cftz93lgexam.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "interop_probing_operational_prod"
  DB_USE_SSL: "true"
  DB_SCHEMA: "prod_probing"
