name: "probing-tenant-event-consumer"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/probing-be-tenant-event-consumer-dev"

configmap:
  APPLICATION_NAME: "pagopa-interop-probing-tenant-event-consumer"
  API_OPERATIONS_BASEURL: "http://probing-eservice-operations.{{.Values.namespace}}:8080"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-tenant-event-consumer"

deployment:
  env:
  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    KAFKA_TOPIC: "common-kafka.CATALOG_TOPIC"
  envFromSecrets:
  envFromFieldRef:
    KAFKA_CLIENT_ID: "metadata.name"
