name: "probing-be-telemetry-writer"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/probing-be-telemetry-writer-{{.Values.local.env}}"

configmap:
  INTEROP_PROBING_TELEMETRY_WRITER_NAME: "pagopa-interop-probing-telemetry-writer"
  SQS_ENDPOINT_TELEMETRY_RESULT_QUEUE: "https://sqs.eu-south-1.amazonaws.com/774300547186/probing-telemetry-record-{{.Values.local.env}}"
  SQS_LONG_POLL_WAIT_TIME_SECONDS: "3"

deployment:
  envFromConfigmaps:
    INFLUX_DB_URL: "common-probing-analytics.INFLUX_INSTANCE_ENDPOINT"
    INFLUX_ORG: "common-probing-analytics.INFLUX_INSTANCE_ORG"
    INFLUX_BUCKET: "common-probing-analytics.INFLUX_INSTANCE_BUCKET"
    INFLUX_PRECISION: "common-probing-analytics.INFLUX_PRECISION"
  envFromSecrets:
    INFLUX_TOKEN: "prod-probing-analytics-db-telemetry-writer-user.token"
