apiVersion: v1
kind: ConfigMap
metadata:
  name: common-kafka
  namespace: dev
data:
  KAFKA_BROKERS: "b-2.iam.interopplatformevents.2doelu.c2.kafka.eu-south-1.amazonaws.com:14002,b-1.iam.interopplatformevents.2doelu.c2.kafka.eu-south-1.amazonaws.com:14001,b-3.iam.interopplatformevents.2doelu.c2.kafka.eu-south-1.amazonaws.com:14003"
  CATALOG_TOPIC: "outbound.dev_catalog.events"
  TENANT_TOPIC: "outbound.dev_tenant.events"
