apiVersion: v1
kind: ConfigMap
metadata:
  name: common-kafka
  namespace: dev
data:
  KAFKA_BROKERS: "b-3.interopplatformevents.2doelu.c2.kafka.eu-south-1.amazonaws.com:9098,b-2.interopplatformevents.2doelu.c2.kafka.eu-south-1.amazonaws.com:9098,b-1.interopplatformevents.2doelu.c2.kafka.eu-south-1.amazonaws.com:9098"
  CATALOG_TOPIC: "event-store.dev_catalog.events"
  TENANT_TOPIC: "event-store.dev_tenant.events"