namespace: "prod"

cronjob:
  env:
    LOG_LEVEL: "info"
  image:
    repositoryPrefix: "861877745473.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

local:
  awsAccountId: "861877745473"
  env: "prod"
