name: "probing-be-scheduler"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/probing-be-scheduler-dev"

configmap:
  INTEROP_PROBING_SCHEDULER_NAME: "pagopa-interop-probing-scheduler"
  API_OPERATIONS_BASEURL: "http://probing-be-eservice-operations.{{.Values.namespace}}:8080"
  SQS_ENDPOINT_POLL_QUEUE: "https://sqs.eu-south-1.amazonaws.com/774300547186/probing-poll-dev"
  SCHEDULER_LIMIT: "50"
  SCHEDULER_CRON_EXPRESSION: "*/3 * * * *"
