name: "probing-scheduler"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/probing-be-scheduler-dev"

configmap:
  INTEROP_PROBING_SCHEDULER_NAME: "pagopa-interop-probing-scheduler"
  API_OPERATIONS_BASEURL: "http://probing-eservice-operations.{{.Values.namespace}}:8080"
  SQS_ENDPOINT_POLL_QUEUE: "https://sqs.eu-south-1.amazonaws.com/774300547186/probing-eservice-operations-poll-queue-dev"
  SCHEDULER_LIMIT: "10"
  SCHEDULER_CRON_EXPRESSION: "59 59 23 31 12 1"

deployment:
  env:
  envFromConfigmaps:
  envFromSecrets:
  envFromFieldRef:
