name: "probing-api"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/probing-be-api-dev"

service:
  create: true
  portName: http
  containerPort: 3010
  targetGroupArn: "arn:aws:elasticloadbalancing:eu-south-1:774300547186:targetgroup/dev-api/56f5036c29f7eff7"
  targetType: "ip"
  ipAddressType: "ipv4"

configmap:
  API_OPERATIONS_BASEURL: "http://probing-eservice-operations.{{.Values.namespace}}:3000"

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: "3010"
    INTEROP_PROBING_API_APP_NAME: "pagopa-interop-probing-api"
    TOLERANCE_MULTIPLIER_IN_MINUTES: "3"
    CORS_ORIGIN_ALLOWED: "*"
  envFromConfigmaps:
  envFromSecrets:
